//Shamelessly ripped from the example plugin here https://github.com/katalon-studio/katalon-recorder-sample-plugin/blob/master/background.js

// Chrome Extension ID: ljdobmomdgdljniojadhoplhkpialdid
// Firefox Extension ID: {91f05833-bab1-4fb1-b9e4-187091a4d75d}

var extensionId = bowser.firefox ? '{91f05833-bab1-4fb1-b9e4-187091a4d75d}' : 'ljdobmomdgdljniojadhoplhkpialdid';

/*
Periodically send a message to Katalon Recorder with a list of capabilities. If Katalon Recorder does not receive any message for 2 minutes, it will stop communicating with the plugin.
Message structure:
{
    type: 'katalon_recorder_register',
    payload: {
        capabilities: [
            {
                id: <string: unique ID for capability>,
                summary: <string: user-friendly name, e.g script format>,
                type: <right now only 'export' is available>
            }
        ]
    }
}
*/
function register() {
    chrome.runtime.sendMessage(
        extensionId,
        {
            type: 'katalon_recorder_register',
            payload: {
                capabilities: [
                    {
                        id: 'perlSRD', // unique ID for each capability
                        summary: 'Perl (Selenium::Remote::Driver)', // user-friendly name
                        type: 'export' // for now only 'export' is available
                    }
                ]
            }
        }
    );
}

register();

setInterval(register, 60 * 1000);

/*
Message sent from Katalon Recorder for the plugin to process.
{
    type: <right now only 'katalon_recorder_export' is available>,
    payload: {
        capabilityId: <sent from plugin in katalon_recorder_register message, use this ID to differentiate between capabilites>
        commands: [
            {
                command: <command name>,
                target: <command target>,
                value: <command value>
            }
        ]
    }
}
Response structure when message.type === 'katalon_recorder_export':
{
    status: <boolean - whether the access was processed successfully>,
    payload: {
        content: <the exported script>,
        extension: <extension when user wants to download the exported script>,
        mimetype: <Katalon Recorder's code editor will use this mimetype to provide syntax highlighting>
    }
}
*/

window.hasSentHeader = 0;

chrome.runtime.onMessageExternal.addListener(function(message, sender, sendResponse) {
    if (message.type === 'katalon_recorder_export') {
        var payload = message.payload;
        var commands = payload.commands;

		//XXX no idea how to do done_testing() at the end, not sure if we have a way to do a footer like in ide-plugin.js
		var driver_class = bowser.firefox ? 'Selenium::Firefox' : 'Selenium::Chrome';
        var header_content = "use strict;\nuse warnings;\n\nuse "+driver_class+";use Test::More;\n\nmy $driver = "+driver_class+"->new();";
		var content = window.hasSentHeader ? '' : header_content;
		window.hasSentHeader = 1;

        var extension = '';
        var mimetype = '';

        console.log(payload,commands);

        switch (payload.capabilityId) {
            case 'perlSRD':
                for (var i = 0; i < commands.length; i++) {
                    var command = commands[i];
                    content += processCommand(command.command,command.target,command.value);
                }
                extension = 'pl';
				mimetype  = 'text/x-script.perl';
                break;
            default:
                content = 'Invalid capability ID';
                extension = 'txt';
				mimetype = 'text/plain';
        }

        sendResponse({
            status: true,
            payload: {
                content: content,
                extension: extension,
                mimetype: mimetype
            }
        });
    }
});

//Build mapping of command -> S::R::D command
window.commandMap = {
	"addLocationStrategy": 0,
	"addLocationStrategyAndWait": 0,
	"addScript": 0,
	"addScriptAndWait": 0,
	"addSelection": 0,
	"addSelectionAndWait": 0,
	"allowNativeXpath": 0,
	"allowNativeXpathAndWait": 0,
	"altKeyDown": 0,
	"altKeyDownAndWait": 0,
	"altKeyUp": 0,
	"altKeyUpAndWait": 0,
	"answerOnNextPrompt": 0,
	"assertAlert": 0,
	"assertAlertNotPresent": 0,
	"assertAlertPresent": 0,
	"assertAllButtons": 0,
	"assertAllFields": 0,
	"assertAllLinks": 0,
	"assertAllWindowIds": 0,
	"assertAllWindowNames": 0,
	"assertAllWindowTitles": 0,
	"assertAttribute": 0,
	"assertAttributeFromAllWindows": 0,
	"assertBodyText": 0,
	"assertChecked": 0,
	"assertConfirmation": 0,
	"assertConfirmationNotPresent": 0,
	"assertConfirmationPresent": 0,
	"assertCookie": 0,
	"assertCookieByName": 0,
	"assertCookieNotPresent": 0,
	"assertCookiePresent": 0,
	"assertCursorPosition": 0,
	"assertEditable": 0,
	"assertElementHeight": 0,
	"assertElementIndex": 0,
	"assertElementNotPresent": 0,
	"assertElementPositionLeft": 0,
	"assertElementPositionTop": 0,
	"assertElementPresent": 0,
	"assertElementWidth": 0,
	"assertEval": 0,
	"assertExpression": 0,
	"assertHtmlSource": 0,
	"assertLocation": 0,
	"assertMouseSpeed": 0,
	"assertNotAlert": 0,
	"assertNotAllButtons": 0,
	"assertNotAllFields": 0,
	"assertNotAllLinks": 0,
	"assertNotAllWindowIds": 0,
	"assertNotAllWindowNames": 0,
	"assertNotAllWindowTitles": 0,
	"assertNotAttribute": 0,
	"assertNotAttributeFromAllWindows": 0,
	"assertNotBodyText": 0,
	"assertNotChecked": 0,
	"assertNotConfirmation": 0,
	"assertNotCookie": 0,
	"assertNotCookieByName": 0,
	"assertNotCursorPosition": 0,
	"assertNotEditable": 0,
	"assertNotElementHeight": 0,
	"assertNotElementIndex": 0,
	"assertNotElementPositionLeft": 0,
	"assertNotElementPositionTop": 0,
	"assertNotElementWidth": 0,
	"assertNotEval": 0,
	"assertNotExpression": 0,
	"assertNotHtmlSource": 0,
	"assertNotLocation": 0,
	"assertNotMouseSpeed": 0,
	"assertNotOrdered": 0,
	"assertNotPrompt": 0,
	"assertNotSelectOptions": 0,
	"assertNotSelectedId": 0,
	"assertNotSelectedIds": 0,
	"assertNotSelectedIndex": 0,
	"assertNotSelectedIndexes": 0,
	"assertNotSelectedLabel": 0,
	"assertNotSelectedLabels": 0,
	"assertNotSelectedValue": 0,
	"assertNotSelectedValues": 0,
	"assertNotSomethingSelected": 0,
	"assertNotSpeed": 0,
	"assertNotTable": 0,
	"assertNotText": 0,
	"assertNotTitle": 0,
	"assertNotValue": 0,
	"assertNotVisible": 0,
	"assertNotWhetherThisFrameMatchFrameExpression": 0,
	"assertNotWhetherThisWindowMatchWindowExpression": 0,
	"assertNotXpathCount": 0,
	"assertOrdered": 0,
	"assertPrompt": 0,
	"assertPromptNotPresent": 0,
	"assertPromptPresent": 0,
	"assertSelectOptions": 0,
	"assertSelectedId": 0,
	"assertSelectedIds": 0,
	"assertSelectedIndex": 0,
	"assertSelectedIndexes": 0,
	"assertSelectedLabel": 0,
	"assertSelectedLabels": 0,
	"assertSelectedValue": 0,
	"assertSelectedValues": 0,
	"assertSomethingSelected": 0,
	"assertSpeed": 0,
	"assertTable": 0,
	"assertText": 0,
	"assertTextNotPresent": 0,
	"assertTextPresent": 0,
	"assertTitle": 0,
	"assertValue": 0,
	"assertVisible": 0,
	"assertWhetherThisFrameMatchFrameExpression": 0,
	"assertWhetherThisWindowMatchWindowExpression": 0,
	"assertXpathCount": 0,
	"assignId": 0,
	"assignIdAndWait": 0,
	"break": 0,
	"back": "navigate->back()",
	"captureEntirePageScreenshot": 0,
	"captureEntirePageScreenshotAndWait": 0,
	"check": 0,
	"checkAndWait": 0,
	"chooseCancelOnNextConfirmation": 0,
	"chooseOkOnNextConfirmation": 0,
	"chooseOkOnNextConfirmationAndWait": 0,
	"click": "click(%)",
	"clickAndWait": 0,
	"clickAt": 0,
	"clickAtAndWait": 0,
	"close": "close()",
	"contextMenu": 0,
	"contextMenuAndWait": 0,
	"contextMenuAt": 0,
	"contextMenuAtAndWait": 0,
	"controlKeyDown": 0,
	"controlKeyDownAndWait": 0,
	"controlKeyUp": 0,
	"controlKeyUpAndWait": 0,
	"createCookie": 0,
	"createCookieAndWait": 0,
	"deleteAllVisibleCookies": 0,
	"deleteAllVisibleCookiesAndWait": 0,
	"deleteCookie": 0,
	"deleteCookieAndWait": 0,
	"deselectPopUp": 0,
	"deselectPopUpAndWait": 0,
	"doubleClick": 0,
	"doubleClickAndWait": 0,
	"doubleClickAt": 0,
	"doubleClickAtAndWait": 0,
	"dragAndDrop": 0,
	"dragAndDropAndWait": 0,
	"dragAndDropToObject": 0,
	"dragAndDropToObjectAndWait": 0,
	"dragdrop": 0,
	"dragdropAndWait": 0,
	"echo": 0,
	"fireEvent": 0,
	"fireEventAndWait": 0,
	"focus": 0,
	"focusAndWait": 0,
	"goBack": 0,
	"goBackAndWait": 0,
	"highlight": 0,
	"highlightAndWait": 0,
	"ignoreAttributesWithoutValue": 0,
	"ignoreAttributesWithoutValueAndWait": 0,
	"keyDown": 0,
	"keyDownAndWait": 0,
	"keyPress": 0,
	"keyPressAndWait": 0,
	"keyUp": 0,
	"keyUpAndWait": 0,
	"metaKeyDown": 0,
	"metaKeyDownAndWait": 0,
	"metaKeyUp": 0,
	"metaKeyUpAndWait": 0,
	"mouseDown": 0,
	"mouseDownAndWait": 0,
	"mouseDownAt": 0,
	"mouseDownAtAndWait": 0,
	"mouseDownRight": 0,
	"mouseDownRightAndWait": 0,
	"mouseDownRightAt": 0,
	"mouseDownRightAtAndWait": 0,
	"mouseMove": 0,
	"mouseMoveAndWait": 0,
	"mouseMoveAt": 0,
	"mouseMoveAtAndWait": 0,
	"mouseOut": 0,
	"mouseOutAndWait": 0,
	"mouseOver": 0,
	"mouseOverAndWait": 0,
	"mouseUp": 0,
	"mouseUpAndWait": 0,
	"mouseUpAt": 0,
	"mouseUpAtAndWait": 0,
	"mouseUpRight": 0,
	"mouseUpRightAndWait": 0,
	"mouseUpRightAt": 0,
	"mouseUpRightAtAndWait": 0,
	"open": "get(%)",
	"openWindow": 0,
	"openWindowAndWait": 0,
	"pause": 0,
	"refresh": 0,
	"refreshAndWait": 0,
	"removeAllSelections": 0,
	"removeAllSelectionsAndWait": 0,
	"removeScript": 0,
	"removeScriptAndWait": 0,
	"removeSelection": 0,
	"removeSelectionAndWait": 0,
	"rollup": 0,
	"rollupAndWait": 0,
	"runScript": 0,
	"runScriptAndWait": 0,
	"select": 0,
	"selectAndWait": 0,
	"selectFrame": 0,
	"selectPopUp": 0,
	"selectPopUpAndWait": 0,
	"selectWindow": "switch_to_window(%)",
	"sendKeys": 0,
	"setBrowserLogLevel": 0,
	"setBrowserLogLevelAndWait": 0,
	"setCursorPosition": 0,
	"setCursorPositionAndWait": 0,
	"setMouseSpeed": 0,
	"setMouseSpeedAndWait": 0,
	"setSpeed": 0,
	"setSpeedAndWait": 0,
	"setTimeout": 0,
	"shiftKeyDown": 0,
	"shiftKeyDownAndWait": 0,
	"shiftKeyUp": 0,
	"shiftKeyUpAndWait": 0,
	"store": 0,
	"storeAlert": 0,
	"storeAlertPresent": 0,
	"storeAllButtons": 0,
	"storeAllFields": 0,
	"storeAllLinks": 0,
	"storeAllWindowIds": 0,
	"storeAllWindowNames": 0,
	"storeAllWindowTitles": 0,
	"storeAttribute": 0,
	"storeAttributeFromAllWindows": 0,
	"storeBodyText": 0,
	"storeChecked": 0,
	"storeConfirmation": 0,
	"storeConfirmationPresent": 0,
	"storeCookie": 0,
	"storeCookieByName": 0,
	"storeCookiePresent": 0,
	"storeCursorPosition": 0,
	"storeEditable": 0,
	"storeElementHeight": 0,
	"storeElementIndex": 0,
	"storeElementPositionLeft": 0,
	"storeElementPositionTop": 0,
	"storeElementPresent": 0,
	"storeElementWidth": 0,
	"storeEval": 0,
	"storeExpression": 0,
	"storeHtmlSource": 0,
	"storeLocation": 0,
	"storeMouseSpeed": 0,
	"storeOrdered": 0,
	"storePrompt": 0,
	"storePromptPresent": 0,
	"storeSelectOptions": 0,
	"storeSelectedId": 0,
	"storeSelectedIds": 0,
	"storeSelectedIndex": 0,
	"storeSelectedIndexes": 0,
	"storeSelectedLabel": 0,
	"storeSelectedLabels": 0,
	"storeSelectedValue": 0,
	"storeSelectedValues": 0,
	"storeSomethingSelected": 0,
	"storeSpeed": 0,
	"storeTable": 0,
	"storeText": 0,
	"storeTextPresent": 0,
	"storeTitle": 0,
	"storeValue": 0,
	"storeVisible": 0,
	"storeWhetherThisFrameMatchFrameExpression": 0,
	"storeWhetherThisWindowMatchWindowExpression": 0,
	"storeXpathCount": 0,
	"submit": 0,
	"submitAndWait": 0,
	"type": "find_element(%)->send_keys(%)",
	"typeAndWait": 0,
	"typeKeys": 0,
	"typeKeysAndWait": 0,
	"uncheck": 0,
	"useXpathLibrary": 0,
	"useXpathLibraryAndWait": 0,
	"verifyAlert": 0,
	"verifyAlertNotPresent": 0,
	"verifyAlertPresent": 0,
	"verifyAllButtons": 0,
	"verifyAllFields": 0,
	"verifyAllLinks": 0,
	"verifyAllWindowIds": 0,
	"verifyAllWindowNames": 0,
	"verifyAllWindowTitles": 0,
	"verifyAttribute": 0,
	"verifyAttributeFromAllWindows": 0,
	"verifyBodyText": 0,
	"verifyChecked": 0,
	"verifyConfirmation": 0,
	"verifyConfirmationNotPresent": 0,
	"verifyConfirmationPresent": 0,
	"verifyCookie": 0,
	"verifyCookieByName": 0,
	"verifyCookieNotPresent": 0,
	"verifyCookiePresent": 0,
	"verifyCursorPosition": 0,
	"verifyEditable": 0,
	"verifyElementHeight": 0,
	"verifyElementIndex": 0,
	"verifyElementNotPresent": 0,
	"verifyElementPositionLeft": 0,
	"verifyElementPositionTop": 0,
	"verifyElementPresent": 0,
	"verifyElementWidth": 0,
	"verifyEval": 0,
	"verifyExpression": 0,
	"verifyHtmlSource": 0,
	"verifyLocation": 0,
	"verifyMouseSpeed": 0,
	"verifyNotAlert": 0,
	"verifyNotAllButtons": 0,
	"verifyNotAllFields": 0,
	"verifyNotAllLinks": 0,
	"verifyNotAllWindowIds": 0,
	"verifyNotAllWindowNames": 0,
	"verifyNotAllWindowTitles": 0,
	"verifyNotAttribute": 0,
	"verifyNotAttributeFromAllWindows": 0,
	"verifyNotBodyText": 0,
	"verifyNotChecked": 0,
	"verifyNotConfirmation": 0,
	"verifyNotCookie": 0,
	"verifyNotCookieByName": 0,
	"verifyNotCursorPosition": 0,
	"verifyNotEditable": 0,
	"verifyNotElementHeight": 0,
	"verifyNotElementIndex": 0,
	"verifyNotElementPositionLeft": 0,
	"verifyNotElementPositionTop": 0,
	"verifyNotElementWidth": 0,
	"verifyNotEval": 0,
	"verifyNotExpression": 0,
	"verifyNotHtmlSource": 0,
	"verifyNotLocation": 0,
	"verifyNotMouseSpeed": 0,
	"verifyNotOrdered": 0,
	"verifyNotPrompt": 0,
	"verifyNotSelectOptions": 0,
	"verifyNotSelectedId": 0,
	"verifyNotSelectedIds": 0,
	"verifyNotSelectedIndex": 0,
	"verifyNotSelectedIndexes": 0,
	"verifyNotSelectedLabel": 0,
	"verifyNotSelectedLabels": 0,
	"verifyNotSelectedValue": 0,
	"verifyNotSelectedValues": 0,
	"verifyNotSomethingSelected": 0,
	"verifyNotSpeed": 0,
	"verifyNotTable": 0,
	"verifyNotText": 0,
	"verifyNotTitle": 0,
	"verifyNotValue": 0,
	"verifyNotVisible": 0,
	"verifyNotWhetherThisFrameMatchFrameExpression": 0,
	"verifyNotWhetherThisWindowMatchWindowExpression": 0,
	"verifyNotXpathCount": 0,
	"verifyOrdered": 0,
	"verifyPrompt": 0,
	"verifyPromptNotPresent": 0,
	"verifyPromptPresent": 0,
	"verifySelectOptions": 0,
	"verifySelectedId": 0,
	"verifySelectedIds": 0,
	"verifySelectedIndex": 0,
	"verifySelectedLabel": 0,
	"verifySelectedLabels": 0,
	"verifySelectedValue": 0,
	"verifySelectedValues": 0,
	"verifySomethingSelected": 0,
	"verifySpeed": 0,
	"verifyTable": 0,
	"verifyText": 0,
	"verifyTextNotPresent": 0,
	"verifyTextPresent": 0,
	"verifyTitle": 0,
	"verifyValue": 0,
	"verifyVisible": 0,
	"verifyWhetherThisFrameMatchFrameExpression": 0,
	"verifyWhetherThisWindowMatchWindowExpression": 0,
	"verifyXpathCount": 0,
	"waitForAlert": 0,
	"waitForAlertNotPresent": 0,
	"waitForAlertPresent": 0,
	"waitForAllButtons": 0,
	"waitForAllFields": 0,
	"waitForAllLinks": 0,
	"waitForAllWindowIds": 0,
	"waitForAllWindowNames": 0,
	"waitForAllWindowTitles": 0,
	"waitForAttribute": 0,
	"waitForAttributeFromAllWindows": 0,
	"waitForBodyText": 0,
	"waitForChecked": 0,
	"waitForCondition": 0,
	"waitForConfirmation": 0,
	"waitForConfirmationNotPresent": 0,
	"waitForConfirmationPresent": 0,
	"waitForCookie": 0,
	"waitForCookieByName": 0,
	"waitForCookieNotPresent": 0,
	"waitForCookiePresent": 0,
	"waitForCursorPosition": 0,
	"waitForEditable": 0,
	"waitForElementHeight": 0,
	"waitForElementIndex": 0,
	"waitForElementNotPresent": 0,
	"waitForElementPositionLeft": 0,
	"waitForElementPositionTop": 0,
	"waitForElementPresent": 0,
	"waitForElementWidth": 0,
	"waitForEval": 0,
	"waitForExpression": 0,
	"waitForFrameToLoad": 0,
	"waitForHtmlSource": 0,
	"waitForLocation": 0,
	"waitForMouseSpeed": 0,
	"waitForNotAlert": 0,
	"waitForNotAllButtons": 0,
	"waitForNotAllFields": 0,
	"waitForNotAllLinks": 0,
	"waitForNotAllWindowIds": 0,
	"waitForNotAllWindowNames": 0,
	"waitForNotAllWindowTitles": 0,
	"waitForNotAttribute": 0,
	"waitForNotAttributeFromAllWindows": 0,
	"waitForNotBodyText": 0,
	"waitForNotChecked": 0,
	"waitForNotConfirmation": 0,
	"waitForNotCookie": 0,
	"waitForNotCookieByName": 0,
	"waitForNotCursorPosition": 0,
	"waitForNotEditable": 0,
	"waitForNotElementHeight": 0,
	"waitForNotElementIndex": 0,
	"waitForNotElementPositionLeft": 0,
	"waitForNotElementPositionTop": 0,
	"waitForNotElementWidth": 0,
	"waitForNotEval": 0,
	"waitForNotExpression": 0,
	"waitForNotHtmlSource": 0,
	"waitForNotLocation": 0,
	"waitForNotMouseSpeed": 0,
	"waitForNotOrdered": 0,
	"waitForNotPrompt": 0,
	"waitForNotSelectOptions": 0,
	"waitForNotSelectedId": 0,
	"waitForNotSelectedIds": 0,
	"waitForNotSelectedIndex": 0,
	"waitForNotSelectedIndexes": 0,
	"waitForNotSelectedLabel": 0,
	"waitForNotSelectedLabels": 0,
	"waitForNotSelectedValue": 0,
	"waitForNotSelectedValues": 0,
	"waitForNotSomethingSelected": 0,
	"waitForNotSpeed": 0,
	"waitForNotTable": 0,
	"waitForNotText": 0,
	"waitForNotTitle": 0,
	"waitForNotValue": 0,
	"waitForNotVisible": 0,
	"waitForNotWhetherThisFrameMatchFrameExpression": 0,
	"waitForNotWhetherThisWindowMatchWindowExpression": 0,
	"waitForNotXpathCount": 0,
	"waitForOrdered": 0,
	"waitForPageToLoad": 0,
	"waitForPopUp": 0,
	"waitForPrompt": 0,
	"waitForPromptNotPresent": 0,
	"waitForPromptPresent": 0,
	"waitForSelectOptions": 0,
	"waitForSelectedId": 0,
	"waitForSelectedIds": 0,
	"waitForSelectedIndex": 0,
	"waitForSelectedIndexes": 0,
	"waitForSelectedLabel": 0,
	"waitForSelectedLabels": 0,
	"waitForSelectedValue": 0,
	"waitForSelectedValues": 0,
	"waitForSomethingSelected": 0,
	"waitForSpeed": 0,
	"waitForTable": 0,
	"waitForText": 0,
	"waitForTextNotPresent": 0,
	"waitForTextPresent": 0,
	"waitForTitle": 0,
	"waitForValue": 0,
	"waitForVisible": 0,
	"waitForWhetherThisFrameMatchFrameExpression": 0,
	"waitForWhetherThisWindowMatchWindowExpression": 0,
	"waitForXpathCount": 0,
	"windowFocus": 0,
	"windowFocusAndWait": 0,
	"windowMaximize": 0,
	"windowMaximizeAndWait": 0
};

//XXX I have *no clue* what to do about locator types, it seems? to be target is strategy=locator
function processCommand(command,target,value) {
	if (!window.commandMap[command]) {
		return "die('Command `"+command+"` not supported by recorder, please file bug in Selenium::Remote::Driver github project');\n";
	}
	var locatorArray = target.split('=').reverse();
	var perl_command = window.commandMap[command].replace('%',locatorArray.join('",')).replace('%',value);

	return "$driver->"+perl_command+';\n';
}
